// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwT8otgti4Vavh1awWzdKH5W_-XyzvyRo',
    appId: '1:35918756299:web:fab8a6082f79b23b425e4e',
    messagingSenderId: '35918756299',
    projectId: 'todofire-6e882',
    authDomain: 'todofire-6e882.firebaseapp.com',
    storageBucket: 'todofire-6e882.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEMwqYldTbhpR2nppF9hk8QWswA0G6NGM',
    appId: '1:35918756299:android:374bf38b7e5b314c425e4e',
    messagingSenderId: '35918756299',
    projectId: 'todofire-6e882',
    storageBucket: 'todofire-6e882.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpNfy6_X5IMrqpdDKZdNBNqz26Lh_FfDc',
    appId: '1:35918756299:ios:3367bb2d5212e101425e4e',
    messagingSenderId: '35918756299',
    projectId: 'todofire-6e882',
    storageBucket: 'todofire-6e882.appspot.com',
    iosClientId: '35918756299-n8ct77nfme2aitjkbfj759n83h48il0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpNfy6_X5IMrqpdDKZdNBNqz26Lh_FfDc',
    appId: '1:35918756299:ios:fd791bcc6fb6b3fa425e4e',
    messagingSenderId: '35918756299',
    projectId: 'todofire-6e882',
    storageBucket: 'todofire-6e882.appspot.com',
    iosClientId: '35918756299-mda9v2q6c2ah3en33le7lp44t3rrupg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoWithFirebase.RunnerTests',
  );
}
